---
- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: install pip3
    package: 
     name: python3-pip
     state: present 
  - name: install ansible
    package:
     name: ansible
     state: present

