---
- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: install pip3
    package: 
     name: python3-pip
     state: absent 
  - name: install ansible
    package:
     name: ansible
     state: present
  - name: install /etc/hosts
    copy:
     src: file
     dest: /etc/hosts
     mode: 0644
     owner: root
     group: root
